### ISSUE TITLE
Sprites unintentionally replaced

### ISSUE THREAD

**Issue by NightHackreal** [NightHackreal/TheLeaningTowerofPizza#2]
I tried making a playable Mr. Stick with the value "T", and used Peppino's sprites as base. However, the Peppino sprites ended up being overwritten with Mr. Stick's sprites, even though they are their own separate objects (PeppinoSprite and StickSprite).

**Comment by NightHackreal** [comment]
Right now, the sprites have been replaced and the sticksprite object has been defeated. What I want to know is _how_ this happened, and what to do to make sure it doesn't happen again.

**Comment by basiccube** [comment]
The reason why this happened is because the new Sprite node is using the same SpriteFrames node from the Sprite node that was duplicated to make the new Sprite node. SpriteFrames contains all of the sprites that the Sprite node uses. Making a copy/duplicate of the Sprite node doesn't duplicate the SpriteFrames node with it.

For example, duplicating NoiseSprite and calling it NoisetteSprite will make it still use NoiseSprite's SpriteFrames node, so replacing the sprites in NoisetteSprite will replace the ones in NoiseSprite as well.

Here's the fix:
Select the new Sprite node, then in the inspector do this:
![image](https://github.com/NightHackreal/TheLeaningTowerofPizza/assets/67266535/976e84ee-75e1-4605-9eae-86faa9904d64)
This will duplicate the existing sprites and make them unique for that specific Sprite node, so it won't replace any existing sprites.

**Comment by NightHackreal** [comment]
Ayyy thx :)
